// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (import.meta.env.DEV && SUPABASE_URL) {
  try {
    console.log("SUPABASE_HOST", new URL(import.meta.env.VITE_SUPABASE_URL).host);
  } catch {
    console.log("SUPABASE_HOST", "invalid-url");
  }

  const projectRef = (() => {
    try {
      return new URL(SUPABASE_URL).hostname.split('.')[0] ?? 'desconocido';
    } catch {
      return 'desconocido';
    }
  })();

  console.info('[supabase] Configuración activa', {
    supabaseUrl: SUPABASE_URL,
    projectRef,
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
